# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: updater_recipe_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cupdater_recipe_service.proto\x12\x0eupdater_recipe\"\x07\n\x05\x45mpty\".\n\x07Package\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\r\n\x05\x66iles\x18\x02 \x03(\t\"=\n\x10GetPackagesReply\x12)\n\x08packages\x18\x01 \x03(\x0b\x32\x17.updater_recipe.Package2^\n\x14UpdaterRecipeService\x12\x46\n\x0bGetPackages\x12\x15.updater_recipe.Empty\x1a .updater_recipe.GetPackagesReplyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_PACKAGE = DESCRIPTOR.message_types_by_name['Package']
_GETPACKAGESREPLY = DESCRIPTOR.message_types_by_name['GetPackagesReply']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'updater_recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:updater_recipe.Empty)
  })
_sym_db.RegisterMessage(Empty)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGE,
  '__module__' : 'updater_recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:updater_recipe.Package)
  })
_sym_db.RegisterMessage(Package)

GetPackagesReply = _reflection.GeneratedProtocolMessageType('GetPackagesReply', (_message.Message,), {
  'DESCRIPTOR' : _GETPACKAGESREPLY,
  '__module__' : 'updater_recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:updater_recipe.GetPackagesReply)
  })
_sym_db.RegisterMessage(GetPackagesReply)

_UPDATERRECIPESERVICE = DESCRIPTOR.services_by_name['UpdaterRecipeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=48
  _EMPTY._serialized_end=55
  _PACKAGE._serialized_start=57
  _PACKAGE._serialized_end=103
  _GETPACKAGESREPLY._serialized_start=105
  _GETPACKAGESREPLY._serialized_end=166
  _UPDATERRECIPESERVICE._serialized_start=168
  _UPDATERRECIPESERVICE._serialized_end=262
# @@protoc_insertion_point(module_scope)
